version: "3.9"

services:
  client:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - ${CLIENT_EXTERNAL_PORT}:${CLIENT_INTERNAL_PORT}
    networks:
      - project
    env_file:
      - .env

  users:
    build: ./users
    volumes:
      - ./users:/app
    networks:
      - project
    env_file:
      - .env

  docs:
    build: ./docs
    volumes:
    - ./docs:/app
    networks:
    - project
    env_file:
    - .env

networks:
  project:
    driver: bridge
