version: "3.9"

services:
  users:
    build: ./users
    volumes:
      - ./users:/app
    ports:
      - ${USERS_EXTERNAL_PORT}:${USERS_INTERNAL_PORT}
    networks:
      - project
    env_file:
      - .env

  docs:
    build: ./docs
    volumes:
    - ./docs:/app
    ports:
    - ${DOCS_EXTERNAL_PORT}:${DOCS_INTERNAL_PORT}
    networks:
    - project
    env_file:
    - .env

networks:
  project:
    driver: bridge
